[package]
name = "dotenv_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
once_cell = "1.16.0"
config = "0.10.1"
serde = {version = "1.0.116", features = ["derive"]}